version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - type: volume
        source: s3data
        target: /data
    command: chalice local --host=0.0.0.0 --port=8000
    tty: true
    stdin_open: true
    environment:
        - STORAGE_ROOT=/data
        - BASE_URL=https://localhost:8000
volumes:
  s3data:
